# Learn more about configuring your checkout UI extension:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-10"

[[extensions]]
name = "customer-metafields"
handle = "customer-metafields"
type = "ui_extension"
uid = "a34be24a-33fd-ce84-93a7-2a24a210e1689ffd4123"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration#network-access
# network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration#metafields

[[extensions.metafields]]
namespace = "custom"
key = "card_id"

[[extensions.metafields]]
namespace = "custom"
key = "customer_id"

[[extensions.metafields]]
namespace = "custom"
key = "points"

[[extensions.metafields]]
namespace = "custom"
key = "gender"

[[extensions.metafields]]
namespace = "custom"
key = "birthday"

[[extensions.metafields]]
namespace = "custom"
key = "operator_ordered_for_customer"

# Address metafields for checkout pre-fill
[[extensions.metafields]]
namespace = "custom"
key = "shipping_address"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration#settings-definition

# [extensions.settings]
# [[extensions.settings.fields]]
# key = "banner_title"
# type = "single_line_text_field"
# name = "Banner title"
# description = "Enter a title for the banner"
